#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:07 kanoh Exp $

.include <bsd.own.mk>

CLIENT=		pcilynx_cb.o.gz
KERNOBJ=	pcilynx.o
MODULEOBJ=	pcilynx_stub.o
MKMAN=		no
KERNDRVDIR=	ieee1394

.include "../Makefile.cflags"

.include <bsd.prog.mk>
