#	$ssdlinux: Makefile,v 1.2 2002/12/11 06:28:32 yamagata Exp $
#	$NetBSD: Makefile,v 1.8 1997/03/24 21:59:48 christos Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

SCRIPTS=	shar.sh
MAN=		shar.1

.include <bsd.prog.mk>
