#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:06 kanoh Exp $

.include <bsd.own.mk>

FILES=		daily.conf monthly.conf security.conf weekly.conf
FILESMODE=	444
FILESDIR=	/etc/defaults

.include <bsd.prog.mk>
