#	$ssdlinux: Makefile,v 1.7 2004/02/03 06:14:43 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	screen-
DISTVERSION=	4.0.2
GNU_DIST=	yes
DEPENDENT=	usr.bin/screen

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
