#	$ssdlinux: Makefile,v 1.10 2005/01/27 02:01:07 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	dump-
DISTVERSION=	0.4b39
MASTER_SITES=	http://keihanna.dl.sourceforge.net/sourceforge/dump
DEPENDENT=	lib/dump sbin/dump sbin/restore
DEPENDENT+=	distrib/utils/x_dump

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
