#	$ssdlinux: Makefile,v 1.3 2002/07/02 01:24:03 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	flex-
DISTVERSION=	2.5.4a
NONGNU_DIST=	yes
ALTRENAMEDISTDIR=	mv ${DISTDIR}/flex-2.5.4 ${DISTDIR}/flex
DEPENDENT=	lib/libfl usr.bin/flex

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
