#	$ssdlinux: Makefile,v 1.2 2002/05/25 19:56:00 kanoh Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	procinfo-
DISTVERSION=	18
MASTER_SITES=	ftp://ftp.cistron.nl/pub/people/svm
DEPENDENT=	usr.bin/procinfo

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
