#	$ssdlinux: Makefile,v 1.5 2004/12/15 08:35:26 todoroki Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	rp-pppoe-
DISTVERSION=	3.5
MASTER_SITES=	http://www.roaringpenguin.com/pppoe
DEPENDENT=	usr.sbin/pppoe
DEPENDENT+=	distrib/powerpc-obs2xx/standard/initrd/list_in/pppoe

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
