#	$ssdlinux: Makefile,v 1.6 2004/12/06 03:04:21 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

# Home Page : http://www.libpng.org/pub/png/

DISTNAME=	libpng-
DISTVERSION=	1.2.8
MASTER_SITES=	ftp://swrinde.nde.swri.edu/pub/png/src
EXTRACT_SUFX=	tar.bz2
DEPENDENT=	lib/libpng

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
