#	$ssdlinux: Makefile,v 1.2 2002/10/23 06:53:47 yamagata Exp $

.include <bsd.own.mk>

CLIENT=		aha152x_cs
MODULEOBJ=	aha152x_stub.o
KERNOBJ=	aha152x.o
MAN=		aha152x_cs.4
KERNDRVDIR=	scsi

.include "../Makefile.cflags"

.include <bsd.prog.mk>
