#	$ssdlinux: Makefile,v 1.1 2002/07/02 05:17:16 yamagata Exp $

.include <bsd.own.mk>

SCRIPTS=	igawk.sh
SCRIPTSNAME=	igawk

.include "${.CURDIR}/../Makefile.cflags"

.PATH:		${DIST}/awklib/eg/prog ${DIST}/doc

.include <bsd.prog.mk>
