#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:07:52 yamagata Exp $

.include <bsd.own.mk>

FILES=		amiga-de.map amiga-us.map

FILESDIR=	${BINDIR}/amiga
.PATH:		${.CURDIR}/../../../../dist/kbd/data/keymaps/amiga

.include <bsd.prog.mk>
