#	$ssdlinux: Makefile,v 1.1 2002/07/05 09:34:17 yamagata Exp $

.include <bsd.own.mk>

LIB=		common
SRCS=		log.c socket.c recv.c util.c
MKPIC=		no
MKLINKLIB=	no

.include "${.CURDIR}/../Makefile.cflags"

.include <bsd.lib.mk>
