#	$ssdlinux: Makefile,v 1.3 2003/06/03 05:17:09 yamagata Exp $

.include <bsd.own.mk>

TEXINFO=	gettext.texi
INFOFLAGS=	-I${.CURDIR}/../../../dist/gettext/gettext-tools/doc

.PATH:		${.CURDIR}/../../../dist/gettext/gettext-tools/doc

.include <bsd.info.mk>
