#	$ssdlinux: Makefile,v 1.3 2004/11/09 02:10:45 todoroki Exp $

.include <bsd.own.mk>

SUBDIR= ath_hal		ath_pci		ath_rate_onoe \
	wlan		wlan_acl	wlan_ccmp \
	wlan_tkip	wlan_wep	wlan_xauth

.include <bsd.subdir.mk>
