#	$ssdlinux: Makefile,v 1.3 2002/12/12 08:54:52 yamagata Exp $
#	$NetBSD: Makefile,v 1.5 1997/10/10 09:26:43 lukem Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>

PROG=		lptest
BINDIR=		/usr/sbin

.include "${.CURDIR}/../Makefile.cflags"

.PATH:		${DIST}/${PROG}

.include <bsd.prog.mk>
