#	$ssdlinux: Makefile,v 1.4 2002/07/02 06:48:33 yamagata Exp $
#	$NetBSD: Makefile,v 1.3 2001/09/02 22:16:58 wiz Exp $

PROG=		texindex

.include <bsd.prog.mk>

.PATH:		${DIST}/texinfo/util ${DIST}/texinfo/doc
