#	$ssdlinux: Makefile.cflags,v 1.1.1.1 2002/05/02 13:37:06 kanoh Exp $
CLIENT_PATH=	'"PATH=/usr/ucb:/usr/bin:/usr/sbin:/bin:/sbin"'
CPPFLAGS+=	-DLINUX_MAJOR=$(KERNEL_MAJOR) -DLINUX_MINOR=$(KERNEL_MINOR)
CPPFLAGS+=	-D_PATH_DHCPD_DB=\"/var/db/dhcpd.leases\"
CPPFLAGS+=	-D_PATH_DHCLIENT_DB=\"/var/db/dhclient.leases\"
CPPFLAGS+=	-D_PATH_DHCLIENT_SCRIPT=\"/etc/dhclient-script\"
