#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:07 kanoh Exp $

.include <bsd.own.mk>

CLIENT=		qlogic_cs
MODULEOBJ=	qlogic_stub.o
KERNOBJ=	qlogicfas.o
MKMAN=		no
KERNDRVDIR=	scsi

.include "../Makefile.cflags"

.include <bsd.prog.mk>
