#	$ssdlinux: Makefile,v 1.4 2005/03/02 06:00:22 yamagata Exp $

.include <bsd.own.mk>

SUBDIR=	util libcom_err libss libe2p libext2fs libuuid libblkid
SUBDIR+=	e2initrd_helper

.include <bsd.subdir.mk>
