#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:11:54 yamagata Exp $

.include <bsd.own.mk>

FILES=		azerty.map be-latin1.map fr-latin1.map fr-latin9.map fr-pc.map
FILES+=		fr.map wangbe.map wangbe2.map

FILESDIR=	${BINDIR}/azerty
.PATH:		${.CURDIR}/../../../../../dist/kbd/data/keymaps/i386/azerty

.include <bsd.prog.mk>
