#	$ssdlinux: Makefile,v 1.1 2002/05/13 08:18:26 kanoh Exp $
#	$NetBSD: Makefile,v 1.7 1998/04/20 14:16:01 lukem Exp $

PROG=	rlog
LINKS=	${BINDIR}/rlog ${BINDIR}/rcslog
MLINKS=	rlog.1 rcslog.1

.include <bsd.prog.mk>
