#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:08:29 yamagata Exp $

.include <bsd.own.mk>

FILES=		atari-de.map  atari-se.map atari-uk-falcon.map  atari-us.map

FILESDIR=	${BINDIR}/atari
.PATH:		${.CURDIR}/../../../../dist/kbd/data/keymaps/atari

.include <bsd.prog.mk>
