#	$ssdlinux: Makefile,v 1.11 2005/02/14 01:39:59 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	libtool-
DISTVERSION=	1.5.14
GNU_DIST=	yes
DEPENDENT=	usr.bin/libtool

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
