#	$ssdlinux: Makefile,v 1.1 2005/03/10 08:43:45 yamagata Exp $

.include <bsd.own.mk>

PROG=		anvil
MANPREFIX=	8
MAN=		${PROG}.${MANPREFIX}

DIST=		${.CURDIR}/../../../dist/postfix
.PATH:		${DIST}/src/${PROG} ${DIST}/man/man${MANPREFIX}

.include <bsd.prog.mk>
