#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:14:29 yamagata Exp $

.include <bsd.own.mk>

FILES=  croat.map   		cz-us-qwertz.map     de-latin1-nodeadkeys.map   
FILES+= de-latin1.map   	de.map   	     de_CH-latin1.map   
FILES+= fr_CH-latin1.map   	fr_CH.map   	     hu.map   
FILES+= sg-latin1-lk450.map   	sg-latin1.map        sg.map   
FILES+= sk-prog-qwertz.map   	sk-qwertz.map        slovene.map   

FILESDIR=	${BINDIR}/qwertz
.PATH:		${.CURDIR}/../../../../../dist/kbd/data/keymaps/i386/qwertz

.include <bsd.prog.mk>
