#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:09:18 yamagata Exp $

.include <bsd.own.mk>

FILES=  sun-pl-altgraph.map   	sun-pl.map   		sundvorak.map   
FILES+= sunkeymap.map   	sunt4-es.map   		sunt4-fi-latin1.map   
FILES+= sunt4-no-latin1.map   	sunt5-cz-us.map   	sunt5-de-latin1.map   
FILES+= sunt5-es.map   		sunt5-fi-latin1.map     sunt5-fr-latin1.map   
FILES+= sunt5-ru.map   		sunt5-uk.map   		sunt5-us-cz.map   

FILESDIR=	${BINDIR}/sun
.PATH:		${.CURDIR}/../../../../dist/kbd/data/keymaps/sun

.include <bsd.prog.mk>
