#	$ssdlinux: Makefile.inc,v 1.1.1.1 2002/05/02 13:37:09 kanoh Exp $
#	$NetBSD: Makefile.inc,v 1.4 1997/10/13 11:19:50 lukem Exp $
#	from: @(#)Makefile.inc	8.1 (Berkeley) 6/5/93

BINDIR?=	/usr/share
WARNS?=		1
NONLS=		yes
