#	$ssdlinux: Makefile,v 1.1 2004/05/24 05:48:04 yamagata Exp $

.include <bsd.own.mk>

PROG=		qmqp-sink
MKMAN=		no

DIST=		${.CURDIR}/../../../dist/postfix
.PATH:		${DIST}/src/smtpstone

.include <bsd.prog.mk>
