#	$ssdlinux: Makefile,v 1.12 2005/03/15 02:32:31 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	gettext-
DISTVERSION=	0.14.3
GNU_DIST=	yes
DEPENDENT=	usr.bin/gettext

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
