#	$ssdlinux: Makefile.inc,v 1.1.1.1 2002/05/02 13:37:10 kanoh Exp $
#	$NetBSD: Makefile.inc,v 1.4 1997/10/18 13:05:22 lukem Exp $

.if exists(${.CURDIR}/../../Makefile.inc)
.include "${.CURDIR}/../../Makefile.inc"
.endif
