#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:12:22 yamagata Exp $

.include <bsd.own.mk>

FILES=		ANSI-dvorak.map dvorak-l.map dvorak-r.map dvorak.map

FILESDIR=	${BINDIR}/dvorak
.PATH:		${.CURDIR}/../../../../../dist/kbd/data/keymaps/i386/dvorak

.include <bsd.prog.mk>
