#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:15:06 yamagata Exp $

.include <bsd.own.mk>

SUBDIR=		azerty dvorak fgGIod include qwerty qwertz

FILES=		README
SCRIPTS=	mk_modmap

FILESDIR=	${BINDIR}/i386
SCRIPTDIR=	${BINDIR}/i386
.PATH:		${.CURDIR}/../../../../dist/kbd/data/keymaps/i386

.include <bsd.prog.mk>
.include <bsd.subdir.mk>
