#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:13 kanoh Exp $

.include <bsd.own.mk>

SUBDIR=		named rndc
SUBDIR+=	rndc-confgen
SUBDIR+=	dnssec-keygen dnssec-makekeyset dnssec-signkey dnssec-signzone
SUBDIR+=	named-checkconf named-checkzone

.include <bsd.subdir.mk>
