#	$ssdlinux: Makefile,v 1.12 2005/02/14 02:03:42 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	file-
DISTVERSION=	4.13
MASTER_SITES=	ftp://ftp.fu-berlin.de/unix/tools/file
DEPENDENT=	usr.bin/file

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
