#	$ssdlinux: Makefile.inc,v 1.1 2003/04/07 06:45:45 kanoh Exp $
SRCTOPDIR=	${.CURDIR}/../../..
INITRDDIR=	${.CURDIR}/../initrd${EXTENSION}
INITRD_FS=	ramdisk.image${EXTENSION}
INITRD_FS_GZ=	${INITRD_FS}.gz
