#	$ssdlinux: Makefile,v 1.4 2004/01/19 05:29:43 yamagata Exp $

.include <bsd.own.mk>

FILES=  bg-cp1251.map           bg-cp855.map          bg_bds-cp1251.map
FILES+= bg_bds-utf8.map         bg_pho-cp1251.map     bg_pho-utf8.map
FILES+= br-abnt.map   	        br-abnt2.map   
FILES+= br-latin1-abnt2.map   	br-latin1-us.map      by.map   
FILES+= cf.map   		cz-cp1250.map         cz-lat2-prog.map   
FILES+= cz-lat2.map   		cz.map   	      defkeymap.map   
FILES+= defkeymap_V1.0.map   	dk-latin1.map         dk.map   
FILES+= emacs.map   		emacs2.map   	      es-cp850.map   
FILES+= es.map   		et-nodeadkeys.map     et.map   
FILES+= fi-latin1.map		fi-latin9.map
FILES+= fi.map			gr-pc.map   
FILES+= gr.map   		hu101.map   	      hypermap.m4
FILES+= il-heb.map
FILES+= il-phonetic.map   	il.map   	      is-latin1.map   
FILES+= is-latin1-us.map   
FILES+= it-ibm.map   		it.map   	      it2.map   
FILES+= jp106.map   		la-latin1.map         lt.baltic.map   
FILES+= lt.l4.map   		lt.map   	      mk-cp1251.map   
FILES+= mk-utf.map   		mk.map   	      mk0.map   
FILES+= nl.map   		nl2.map
FILES+= no-latin1.doc		no-latin1.map         no.map   
FILES+= pc110.map   		pl.map   	      pl2.map   
FILES+= pt-latin1.map		pt-latin9.map
FILES+= ro_win.map		ru-cp1251.map   
FILES+= ru-ms.map   		ru-yawerty.map        ru.map   
FILES+= ru1.map   		ru2.map   	      ru3.map   
FILES+= ru4.map   		ru_win.map	      se-fi-ir209.map
FILES+=	se-fi-lat6.map		se-ir209.map	      se-lat6.map
FILES+= sk-prog-qwerty.map	sk-qwerty.map         sr-cy.map
FILES+= sv-latin1.map		tr_q-latin5.map
FILES+= tralt.map   		trq.map   	      ua-utf-ws.map   
FILES+= ua-utf.map   		ua-ws.map   	      ua.map   
FILES+= uk.map   		us-acentos.map        us.map   

FILESDIR=	${BINDIR}/qwerty
.PATH:		${.CURDIR}/../../../../../dist/kbd/data/keymaps/i386/qwerty

.include <bsd.prog.mk>
