#	$ssdlinux: Makefile,v 1.3 2003/09/11 09:04:17 yamagata Exp $

.include <bsd.own.mk>

PROG=		pgawk
SRCS=		eval_p.c profile_p.c
MKMAN=		no

.include "${.CURDIR}/../Makefile.cflags"
.include "${.CURDIR}/../Makefile.ldflags"

.include <bsd.prog.mk>
