#	$ssdlinux: Makefile,v 1.4 2003/03/14 06:18:17 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	groff-
DISTVERSION=	1.17.2
GNU_DIST=	yes
DEPENDENT=	usr.bin/groff

LOCAL_PATCHFILES=	groff-1.17.2-pre-html_cc.patch
DISTRELEASE=	2

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
