#	$ssdlinux: Makefile,v 1.5 2003/06/12 08:49:03 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	uucp-
DISTVERSION=	1.07
GNU_DIST=	yes
DEPENDENT=	lib/uucp libexec/uucp usr.bin/uucp

LOCAL_PATCHFILES=	uucp-1.07-policy_h.patch

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
