#	$ssdlinux: Makefile,v 1.2 2004/05/24 05:48:04 yamagata Exp $

.include <bsd.own.mk>

SUBDIR=	postfix smtp-source smtp-sink qmqp-source qmqp-sink sendmail \
	postalias postcat postconf postdrop \
	postkick postlock postlog postmap postqueue postsuper 

.include <bsd.subdir.mk>

