#	$ssdlinux: Makefile,v 1.7 2004/12/15 08:35:25 todoroki Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	less-
DISTVERSION=	382
GNU_DIST=	yes
DEPENDENT=	usr.bin/less
DEPENDENT+=	distrib/powerpc-obs2xx/standard/initrd/list_in/cfbin

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
