#	$ssdlinux: Makefile,v 1.4 2005/03/15 01:18:49 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	psmisc-
DISTVERSION=	21.6
MASTER_SITES=	http://psmisc.sourceforge.net
DEPENDENT=	usr.bin/psmisc
DEPENDENT+=	distrib/powerpc-obs2xx/standard/initrd/list_in/pcmcia-cs.base

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
