#	$ssdlinux: Makefile,v 1.8 2004/08/24 04:07:57 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	gawk-
DISTVERSION=	3.1.4
EXTRACT_SUFX=	tar.bz2
GNU_DIST=	yes
DEPENDENT=	usr.bin/gawk

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
