#	$ssdlinux: Makefile,v 1.3 2002/06/05 03:26:09 yamagata Exp $

.include <bsd.own.mk>

DISTNAME=	m4
CONFIGURE_ENV=
CONFIGURE_OPTIONS=
GMAKE_ENV=
GMAKE_OPTIONS=	CFLAGS="-O2"
INSTALL_STRIP=	no
GNU_STRIP=	${BINDIR}/m4

.include <bsd.gnu.mk>
