#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:07 kanoh Exp $

.include <bsd.own.mk>

CLIENT=		parport_cs
MKMAN=		no

.include "../Makefile.cflags"

CPPFLAGS+=	-DMODVERSIONS

.include <bsd.prog.mk>
