#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:07 kanoh Exp $

.include <bsd.own.mk>

CLIENT=		ohci1394_cb
MODULEOBJ=	ohci1394_stub.o
KERNOBJ=	ohci1394.o
MKMAN=		no
KERNDRVDIR=	ieee1394

.include "../Makefile.cflags"

.include <bsd.prog.mk>
