#	$ssdlinux: Makefile,v 1.2 2002/06/06 06:08:51 yamagata Exp $

.include <bsd.own.mk>

PROG=		postlock

DIST=		${.CURDIR}/../../../dist/postfix
.PATH:		${DIST}/src/${PROG} ${DIST}/man/man1

.include <bsd.prog.mk>
