#	$ssdlinux: Makefile,v 1.10 2004/10/01 08:57:05 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	rsync-
DISTVERSION=	2.6.3
MASTER_SITES=	ftp://rsync.samba.org/pub/rsync
DEPENDENT=	usr.bin/rsync

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
