#	$ssdlinux: Makefile,v 1.5 2004/05/27 03:04:46 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	make-
DISTVERSION=	3.80
EXTRACT_SUFX=	tar.bz2
GNU_DIST=	yes
DEPENDENT=	usr.bin/make

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
