#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:07 kanoh Exp $

.include <bsd.own.mk>

MODULE=		pcmcia_core
MODULEOBJ=	cs.o cistpl.o rsrc_mgr.o bulkmem.o cardbus.o pci_fixup.o
MAN=		pcmcia_core.4

.include "../Makefile.cflags"

.include <bsd.prog.mk>
