#	$ssdlinux: Makefile,v 1.1 2002/05/13 08:02:28 kanoh Exp $
#	$NetBSD: Makefile,v 1.7 1997/10/18 04:42:03 lukem Exp $

SUBDIR+=lib ci co ident merge rcs rcsclean rcsdiff rcsfreeze rcsmerge rlog

all-ci all-co all-ident all-merge all-rcs all-rcsclean all-rcsdiff \
    all-rcsfreeze all-rcsmerge all-rlog: all-lib

.include <bsd.subdir.mk>
