#	$ssdlinux: Makefile,v 1.2 2002/06/06 06:16:54 yamagata Exp $

.include <bsd.own.mk>

PROG=		pppoe-relay
SRCS=		relay.c if.c debug.c common.c
MAN=		${PROG}.8

NOGCCERROR=	yes

.include <bsd.prog.mk>
