#	$ssdlinux: Makefile,v 1.3 2003/10/14 06:06:27 yamagata Exp $

.include <bsd.own.mk>

MODULE=		ov511
MKMAN=		no

.include "${.CURDIR}/../Makefile.cflags"

CPPFLAGS+=	-DEXPORT_SYMTAB

.include <bsd.prog.mk>
