#	$ssdlinux: Makefile,v 1.1 2002/11/08 07:32:29 yamagata Exp $

SCRIPTS=	unicode_start
MAN=		${SCRIPTS}.1

DIST=		${.CURDIR}/../../../dist/kbd
.PATH:		${DIST}/src ${DIST}/man/man1

.include <bsd.prog.mk>
