#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:12:50 yamagata Exp $

.include <bsd.own.mk>

FILES=		tr_f-latin5.map trf.map

FILESDIR=	${BINDIR}/fgGIod
.PATH:		${.CURDIR}/../../../../../dist/kbd/data/keymaps/i386/fgGIod

.include <bsd.prog.mk>
