#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:06 kanoh Exp $

.include <bsd.own.mk>

CLIENT=		fdomain_cs
MODULEOBJ=	fdomain_stub.o
KERNOBJ=	fdomain.o
MKMAN=		no
KERNDRVDIR=	scsi

.include "../Makefile.cflags"

.include <bsd.prog.mk>
