/*	$ssdlinux: config.h,v 1.7 2004/07/13 03:03:35 yamagata Exp $	*/
/*
 *	generated by ./configure --disable-rmt
 */
/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define this if you want to include Quick File Access debugging code. */
/* #undef DEBUG_QFA */

/* Define this if you want to include Mac OSX restore compatibility. */
/* #undef DUMP_MACOSX */

/* Define this if you have the blkid library. */
#define HAVE_BLKID 1

/* Define this if you have bzlib compression library. */
#define HAVE_BZLIB 1

/* Define to 1 if you have the `err' function. */
#define HAVE_ERR 1

/* Define to 1 if you have the `errx' function. */
#define HAVE_ERRX 1

/* Define to 1 if you have the <ext2fs/ext2_fs.h> header file. */
#define HAVE_EXT2FS_EXT2_FS_H 1

/* Define if we have the ext2_ino_t type (from e2fsprogs 1.20+). */
#define HAVE_EXT2_INO_T 1

/* Define if we have the s_journal_inum field in struct ext2_super_block. */
#define HAVE_EXT2_JOURNAL_INUM 1

/* Define if you have the glob function. */
#define HAVE_GLOB 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `lchown' function. */
#define HAVE_LCHOWN 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you want to include readline support. */
#define HAVE_READLINE 1

/* Define this if your readline libs have the rl_completion_append_character
   variable. */
#define HAVE_READLINE_CAC 1

/* Define this if your readline libs have the rl_completion_matches library.
   */
#define HAVE_READLINE_RLCM 1

/* Define to 1 if you have the `realpath' function. */
#define HAVE_REALPATH 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `verr' function. */
#define HAVE_VERR 1

/* Define to 1 if you have the `verrx' function. */
#define HAVE_VERRX 1

/* Define to 1 if you have the `vwarn' function. */
#define HAVE_VWARN 1

/* Define to 1 if you have the `vwarnx' function. */
#define HAVE_VWARNX 1

/* Define to 1 if you have the `warn' function. */
#define HAVE_WARN 1

/* Define to 1 if you have the `warnx' function. */
#define HAVE_WARNX 1

/* Define this if you have zlib compression library. */
#define HAVE_ZLIB 1

/* Define this is you want old style F script (no arguments). */
/* #undef OLD_STYLE_FSCRIPT */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define this if you want Large File System support. */
#define USE_LFS 1

/* Define this if you want Quick File Access support. */
#define USE_QFA 1

/* Define to `int64_t' if <sys/types.h> does not define. */
/* #undef quad_t */

/* Define to `uint64_t' if <sys/types.h> does not define. */
/* #undef u_quad_t */
