#!/bin/sh -
#
#	$ssdlinux: weekly,v 1.3 2002/06/04 01:22:41 yamagata Exp $
#	$NetBSD: weekly,v 1.8 1997/03/10 09:45:59 mycroft Exp $
#	from: @(#)weekly	8.2 (Berkeley) 1/2/94
#

PATH=/bin:/sbin:/usr/sbin:/usr/bin:/usr/libexec
export PATH

umask 077

host=`hostname`
echo "Subject: $host weekly run output"

if [ -s /etc/weekly.conf ]; then
	. /etc/weekly.conf
fi

#echo ""
#echo "Removing old .o files:"
#find /usr/src -name '*.o' -atime +21 -print -a -exec rm -f {} \;

# see if /usr/src exists and is local
# before looking there for checked-out files

#if [ -d /usr/src -a \
#  -n "`find -f /usr/src ! -fstype local -prune -or -type d -print -prune`" ];
#then
#	echo "looking for checked out files:"
#	TDIR=/tmp/_checkout$$
#
#	mkdir $TDIR
#	for file in `find -f /usr/src ! -fstype local -prune -or \
#	    -name 'p.*' -print | egrep 'SCCS/p\.'`; do
#		owner=`awk '{ print $3 }' $file`
#		echo "$owner	$file"
#		echo $file >> $TDIR/$owner
#	done | sed -e 's,SCCS/p.,,'
#	if test -n "`ls $TDIR`"; then
#		for file in $TDIR/*; do
#			sed -e 's,SCCS/p.,,' $file | \
#			    Mail -s 'checked out files' `basename $file`
#		done
#	fi
#	rm -rf $TDIR
#fi

echo ""
if [ "$rebuild_locatedb" = YES ] && [ -x /usr/bin/updatedb ]; then
	echo "Rebuilding locate database:"
	/usr/bin/updatedb
else
	echo "Not rebuilding locate database; no /var/db/locatedb"
fi

if [ -f /etc/weekly.local ]; then
	echo ""
	echo "Running /etc/weekly.local:"
	. /etc/weekly.local
fi
