#	$ssdlinux: Makefile,v 1.1 2004/12/17 06:08:35 yamagata Exp $

.include <bsd.own.mk>

DIST=	${.CURDIR}/../../../dist/man-pages/man9
MAN!=	cd ${DIST} && ls -1 *.9

.PATH:	${DIST}

.include <bsd.man.mk>
