#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:09 kanoh Exp $

.include	<bsd.own.mk>

FILES=  8859-1.a0-ff.uni   8859-10.a0-ff.uni  8859-13.a0-ff.uni  8859-14.a0-ff.uni
FILES+= 8859-15.a0-ff.uni  8859-2.a0-ff.uni   8859-3.a0-ff.uni	 8859-4.a0-ff.uni
FILES+= 8859-5.a0-ff.uni   8859-6.a0-ff.uni   8859-7.a0-ff.uni	 8859-8.a0-ff.uni
FILES+= 8859-9.a0-ff.uni   ECMA144.uni	      README		 armscii8.uni
FILES+= ascii.20-7f.uni    cp1250.uni	      cp437.00-1f.uni	 cp437.uni
FILES+= cp737.uni	   cp737a.uni	      cp737b.uni	 cp737c.uni
FILES+= cp850.uni	   cp850a.uni	      cp850b.uni	 cp850z.uni
FILES+= cp865.uni	   cp865a.uni	      cp866.uni		 cp866a.uni
FILES+= cybercafe.uni	   cyralt.uni	      def.uni		 empty.uni
FILES+= ethiopic.uni	   iso01.uni	      iso02.uni		 iso03.uni
FILES+= iso04.uni	   iso05.uni	      iso06.uni		 iso07.uni
FILES+= iso07u.uni	   iso08.uni	      iso09.uni		 iso10.uni
FILES+= iso15.uni	   koi8r.uni	      koi8u.uni		 lat1.uni
FILES+= lat1u.uni	   lat2.uni	      lat2u.uni		 lat4.uni
FILES+= lat4u.uni	   lat7.uni	      lat9u.uni		 lat9v.uni
FILES+= lat9w.uni	   ruscii.uni	      tcvn.uni		 viscii.uni

FILESDIR=	$(BINDIR)/unimaps
.PATH:		${.CURDIR}/../../../dist/kbd/data/unimaps

.include <bsd.prog.mk>
