#	$ssdlinux: Makefile,v 1.6 2002/11/01 07:35:52 yamagata Exp $

.include <bsd.own.mk>

PROG=		dump_tcic
MKMAN=		no
CLEANFILES=	${PROG}.d

CPPFLAGS=	-MD

.include "${.CURDIR}/../Makefile.cflags"

.include <bsd.prog.mk>
