#	$ssdlinux: Makefile,v 1.4 2004/09/27 01:46:20 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	gmp-
DISTVERSION=	4.1.4
EXTRACT_SUFX=	tar.bz2
GNU_DIST=	yes
DEPENDENT=	lib/gmp

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
