#	$ssdlinux: Makefile.inc,v 1.2 2002/12/25 15:21:36 kanoh Exp $

NETKITVERSION=	0.17

SSDSRCDIR=	${.CURDIR}/../..
KERNSRCDIR=	${SSDSRCDIR}/linux
DISTDIR=	${SSDSRCDIR}/dist
DISTFILESDIR=	${SSDSRCDIR}/dist/distfiles
