#	$ssdlinux: Makefile,v 1.1 2005/02/10 09:04:18 todoroki Exp $

.include <bsd.own.mk>

DISTNAME=	libusb
HAVE_DESTDIR= 1
CONFIGURE_FULL_PREFIX= 1
CONFIGURE_ENV=
CONFIGURE_OPTIONS=  --x-includes=no --x-libraries=no
GMAKE_ENV=
GMAKE_OPTIONS=
GMAKE_INSTALL_OPTIONS= DESTDIR=${DESTDIR}
INSTALL_STRIP=  no

.include <bsd.gnu.mk>
