#	$ssdlinux: Makefile,v 1.7 2003/03/31 04:47:09 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	ksymoops-
DISTVERSION=	2.4.9
EXTRACT_SUFX=	tar.bz2
KERN_DISTDIR=	/utils/kernel/ksymoops/v${KERNEL_MAJOR}.${KERNEL_MINOR}
DEPENDENT=	usr.bin/ksymoops

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
