#	$ssdlinux: Makefile,v 1.5 2005/03/10 08:43:33 yamagata Exp $

.include <bsd.own.mk>

SUBDIR=	master error pickup cleanup smtpd local \
	lmtp trivial-rewrite qmgr smtp oqmgr \
	bounce pipe showq qmqpd spawn flush \
	virtual proxymap verify \
	anvil discard scache tlsmgr

.include <bsd.subdir.mk>

