# $ssdlinux: Makefile,v 1.1 2002/06/14 04:10:03 yamagata Exp $
# $NetBSD: Makefile,v 1.2 1999/09/21 06:24:46 cgd Exp $
# From: $FreeBSD: src/usr.bin/mktemp/Makefile,v 1.1 1998/04/14 07:39:56 peter Exp $

PROG=	mktemp

.include <bsd.prog.mk>
