#	$ssdlinux: Makefile,v 1.3 2002/12/12 08:54:52 yamagata Exp $
#	$NetBSD: Makefile,v 1.6 2001/12/12 01:48:52 tv Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

.include <bsd.own.mk>

PROG=		lpf
MAN=		${PROG}.8
BINDIR=		/usr/libexec/lpr

.include "${.CURDIR}/../Makefile.cflags"

.PATH:		${DIST}/filters

.include <bsd.prog.mk>
