#	$ssdlinux: Makefile,v 1.4 2003/10/14 06:09:41 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	ov511-
DISTVERSION=	1.65
MASTER_SITES=	http://alpha.dyndns.org/ov511/download/1.xx/distros
DEPENDENT=	lib/modules/usb/ov511

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
