#	$ssdlinux: Makefile,v 1.3 2002/07/10 07:24:51 yamagata Exp $

.include <bsd.own.mk>

DIST=	${.CURDIR}/../../../dist/man-pages/man5
MAN!=	cd ${DIST} && ls -1 *.5

.PATH:	${DIST}

.include <bsd.man.mk>
