#	$ssdlinux: Makefile,v 1.2 2002/12/25 16:15:14 kanoh Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	ppc-headers-
DISTVERSION=	${GLIBC_VERSION}
DEPENDENT=	cross/powerpc/gcc-core

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
