#	$ssdlinux: Makefile,v 1.6 2004/01/19 05:31:12 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	kbd-
DISTVERSION=	1.12
EXTRACT_SUFX=	tar.bz2
MASTER_SITES=	ftp://ftp.kernel.org/pub/linux/utils/kbd
DEPENDENT=	lib/kbd share/kbd sbin/loadkeys usr.bin/kbd

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
