#	$ssdlinux: Makefile,v 1.4 2004/05/31 07:03:55 yamagata Exp $

.include <bsd.own.mk>

MODULE=		pam_env
CONFFILE=	pam_env.conf
FILES=		pam_env.conf-example

.include "${.CURDIR}/../Makefile.cflags"

.include <bsd.prog.mk>
