#	$ssdlinux: Makefile.inc,v 1.1 2004/11/11 17:13:56 kanoh Exp $
#	$NetBSD: Makefile.inc,v 1.4 1995/02/27 13:21:22 cgd Exp $
#       @(#)Makefile.inc	8.1 (Berkeley) 6/4/93

.PATH: ${.CURDIR}/db

SRCS+=	db.c
