#	$ssdlinux: Makefile,v 1.2 2002/06/06 06:51:55 yamagata Exp $

.include <bsd.own.mk>

LIB=		timed
SRCS=		byteorder.c measure.c cksum.c

DIST=		${.CURDIR}/../../../dist/usagi-tool/src/netkit-timed/timed
.PATH:		${DIST}/lib

libinstall::

.include <bsd.lib.mk>
