#	$ssdlinux: Makefile,v 1.9 2005/01/05 03:33:35 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	texinfo-
DISTVERSION=	4.8
GNU_DIST=	yes
EXTRACT_SUFX=	tar.bz2
DEPENDENT=	usr.bin/texinfo

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
