#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:15 kanoh Exp $

.include <bsd.own.mk>

SUBDIR=		libsm libsmutil libsmdb
SUBDIR+=	sendmail editmap mailstats makemap praliases \
		mail.local rmail smrsh cf vacation

.include <bsd.subdir.mk>

