#	$ssdlinux: Makefile,v 1.5 2003/03/14 06:18:17 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	bison-
DISTVERSION=	1.875
EXTRACT_SUFX=	tar.bz2
GNU_DIST=	yes
LOCAL_PATCHFILES=	bison-1.875-yacc_c.patch
DISTRELEASE=	1
DEPENDENT=	usr.bin/bison

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
