#	$ssdlinux: Makefile.ldflags,v 1.1.1.1 2002/05/02 13:37:06 kanoh Exp $
LDADD+=	-lresolv
LDADD+= -L${LIBIPROUTE2}/libnetlink -lnetlink
LDADD+= -L${LIBIPROUTE2}/libutil -lutil
DPADD+= ${LIBIPROUTE2}/libnetlink/libnetlink.a
DPADD+= ${LIBIPROUTE2}/libutil/libutil.a
