#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:09:59 yamagata Exp $

.include <bsd.own.mk>

FILES+= mac-azerty-layout.inc  mac-euro.map   	      mac-linux-keys-bare.inc
FILES+= mac-qwerty-layout.inc  mac-qwertz-layout.inc

FILESDIR=	${BINDIR}/include
.PATH:		${.CURDIR}/../../../../../dist/kbd/data/keymaps/mac/include

.include <bsd.prog.mk>
