#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:10:49 yamagata Exp $

.include <bsd.own.mk>

FILES=		compose.8859_7 compose.8859_8 compose.latin compose.latin1
FILES+=		compose.latin2 compose.latin3 compose.latin4 vim-compose.latin1

FILESDIR=	${BINDIR}/include
.PATH:		${.CURDIR}/../../../../dist/kbd/data/keymaps/include

.include <bsd.prog.mk>
