#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:09 kanoh Exp $

.include <bsd.own.mk>

DIST=	${.CURDIR}/../../../dist/man-pages/man6
MAN!=	cd ${DIST} && ls -1 *.6

.PATH:	${DIST}

.include <bsd.man.mk>
