#	$ssdlinux: Makefile,v 1.6 2004/10/20 06:51:51 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	ntp-
DISTVERSION=	4.1.2
MASTER_SITES=	ftp://ftp.udel.edu/pub/ntp/ntp4
DEPENDENT=	usr.sbin/ntp

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
