#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:09:59 yamagata Exp $

.include <bsd.own.mk>

FILES=  mac-be.map   		 mac-de-latin1-nodeadkeys.map     mac-de-latin1.map   
FILES+= mac-de_CH.map   	 mac-dk-latin1.map   		  mac-dvorak.map   
FILES+= mac-es.map   		 mac-fi-latin1.map   		  mac-fr.map   
FILES+= mac-fr_CH-latin1.map     mac-it.map   			  mac-pt-latin1.map   
FILES+= mac-se.map   		 mac-template.map   		  mac-uk.map   
FILES+= mac-us.map   

FILESDIR=	${BINDIR}/all
.PATH:		${.CURDIR}/../../../../../dist/kbd/data/keymaps/mac/all

.include <bsd.prog.mk>
