#	$ssdlinux: Makefile,v 1.1 2005/02/10 09:04:18 todoroki Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

# Home Page : http://libusb.sourceforge.net/

DISTNAME=	libusb-
DISTVERSION=	0.1.9
MASTER_SITES=	http://jaist.dl.sourceforge.net/sourceforge/libusb/
DEPENDENT=	lib/libusb usr/sbin/usbutils

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
