#	$ssdlinux: Makefile,v 1.12 2005/02/07 04:47:16 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	sudo-
DISTVERSION=	1.6.8p7
MASTER_SITES=	ftp://ftp.courtesan.com/pub/sudo
DEPENDENT=	usr.bin/sudo usr.sbin/visudo

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
