#	$ssdlinux: Makefile.cflags,v 1.1 2003/06/05 04:53:48 yamagata Exp $

CPPFLAGS+=	-DLOCALEDIR=\"/usr/share/locale\" -DSHAREDIR=\"/usr/share\"
CPPFLAGS+=	-DHAVE_CONFIG_H -I${LIBCUDIR} -I${DIST}/src -I${DIST}/lib
