#	$ssdlinux: Makefile,v 1.2 2004/12/14 04:25:58 todoroki Exp $

.include <bsd.own.mk>
.include "../Makefile.inc"

LIST_S= common flashcfg sh dhcpd modules named ppp pppoe sendmail vtund \
	useradd httpd setup_cgi

.include "${.CURDIR}/../../standard/initrd/Makefile.inc"
