#	$ssdlinux: Makefile,v 1.3 2004/03/05 09:01:15 yamagata Exp $

.include <bsd.own.mk>

SUBDIR=		pppoe libevent pppoe-server pppoe-sniff 
SUBDIR+=	pppoe-relay scripts configs

.include <bsd.subdir.mk>

