#	$ssdlinux: Makefile,v 1.8 2003/12/18 03:48:10 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	autoconf-
DISTVERSION=	2.59
EXTRACT_SUFX=	tar.bz2
GNU_DIST=	yes
DEPENDENT=	usr.bin/autoconf

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
