#	$ssdlinux: Makefile.cflags,v 1.9 2005/03/10 07:11:42 yamagata Exp $
STATIC_IPT=	yes

KERNSRC=		${DIST}/../../linux
IPT_LIB_DIR=		/lib/iptables
IPTABLES_VERSION=	1.3.1

CPPFLAGS+=	-Wall -Wunused -I${KERNSRC}/include -I${DIST}/include
CPPFLAGS+=	-DIPTABLES_VERSION=\"${IPTABLES_VERSION}\"
