#	$ssdlinux: Makefile,v 1.2 2002/05/24 06:11:45 kanoh Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	bc-
DISTVERSION=	1.06
GNU_DIST=	yes
DEPENDENT=	usr.bin/bc

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
