#	$ssdlinux: Makefile,v 1.5 2004/09/06 02:38:44 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	m4-
DISTVERSION=	1.4.2
GNU_DIST=	yes
DEPENDENT=	usr.bin/m4

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
