#	$ssdlinux: Makefile,v 1.2 2002/07/11 00:38:15 yamagata Exp $
#	$NetBSD: Makefile,v 1.10 2001/01/09 03:13:42 lukem Exp $
#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93

SUBDIR=		common_source .WAIT lpc lpd lpq lpr lprm lptest pac filters \
		printcap

.include <bsd.subdir.mk>
