#	$ssdlinux: Makefile.cflags,v 1.3 2002/12/12 09:12:51 yamagata Exp $
#	$NetBSD: Makefile.inc,v 1.5 2001/01/07 08:00:58 enami Exp $

DIST=		${.CURDIR}/../../../dist/lpr
CPPFLAGS=	-I${DIST}/common_source
CPPFLAGS+=	-D_BSD_SOURCE
