#	$ssdlinux: Makefile,v 1.2 2002/11/08 07:06:03 yamagata Exp $

.include <bsd.own.mk>

SUBDIR=	partialfonts

FILES+= 161.cp   		 162.cp   		 163.cp   
FILES+= 164.cp   		 165.cp   		 737.cp   
FILES+= 880.cp   		 928.cp   		 972.cp   
FILES+= Agafari-12.psfu   	 Agafari-14.psfu   	 Agafari-16.psfu   
FILES+= Cyr_a8x14.psfu   	 Cyr_a8x16.psfu   	 Cyr_a8x8.psfu   
FILES+= ERRORS   		 Goha-12.psfu   	 Goha-14.psfu   
FILES+= Goha-16.psfu   		 GohaClassic-12.psfu     GohaClassic-14.psfu   
FILES+= GohaClassic-16.psfu   	 LatArCyrHeb-08.psfu     LatArCyrHeb-14.psfu   
FILES+= LatArCyrHeb-16+.psfu     LatArCyrHeb-16.psfu     LatArCyrHeb-19.psfu   
FILES+= Mik_8x16   		 README.12x22		 README.Arabic
FILES+= README.Cyrillic		 README.Ethiopic	 README.Greek
FILES+= README.Hebrew		 README.cp1250		 README.cybercafe
FILES+= README.drdos		 README.lat0		 README.lat7
FILES+= README.lat9		 README.psfu		 alt-8x14   
FILES+= alt-8x16   		 alt-8x8   		 altc-8x16   
FILES+= aply16.psf   		 arm8.fnt   		 cp1250.psfu   
FILES+= cp850-8x14.psfu   	 cp850-8x16.psfu   	 cp850-8x8.psfu   
FILES+= cp857.08   		 cp857.14   		 cp857.16   
FILES+= cp865-8x14.psfu   	 cp865-8x16.psfu   	 cp865-8x8.psfu   
FILES+= cp866-8x14.psf   	 cp866-8x16.psf   	 cp866-8x8.psf   
FILES+= cybercafe.fnt		 cyr-sun16.psfu
FILES+= default8x16.psfu   	 default8x9.psfu   
FILES+= drdos8x14.psfu   	 drdos8x16.psfu   	 drdos8x6.psfu   
FILES+= drdos8x8.psfu   	 gr737a-8x8.psfu   	 gr737a-9x14.psfu   
FILES+= gr737a-9x16.psfu   	 gr737b-8x11.psfu   	 gr737b-9x16-medieval.psfu   
FILES+= gr737c-8x14.psfu   	 gr737c-8x16.psfu   	 gr737c-8x6.psfu   
FILES+= gr737c-8x7.psfu   	 gr737c-8x8.psfu   	 gr737d-8x16.psfu   
FILES+= gr928-8x16-thin.psfu     gr928-9x14.psfu   	 gr928-9x16.psfu   
FILES+= gr928a-8x14.psfu   	 gr928a-8x16.psfu   	 gr928b-8x14.psfu   
FILES+= gr928b-8x16.psfu   	 iso01-12x22.psfu   	 iso01.08   
FILES+= iso01.14   		 iso01.16   		 iso02-12x22.psfu   
FILES+= iso02.08   		 iso02.14   		 iso02.16   
FILES+= iso03.08   		 iso03.14   		 iso03.16   
FILES+= iso04.08   		 iso04.14   		 iso04.16   
FILES+= iso05.08   		 iso05.14   		 iso05.16   
FILES+= iso06.08   		 iso06.14   		 iso06.16   
FILES+= iso07.14   		 iso07.16   		 iso07u-16.psfu   
FILES+= iso08.08   		 iso08.14   		 iso08.16   
FILES+= iso09.08   		 iso09.14   		 iso09.16   
FILES+= iso10.08   		 iso10.14   		 iso10.16   
FILES+= koi8-14.psf   		 koi8c-8x16   		 koi8r-8x14   
FILES+= koi8r-8x16   		 koi8r-8x8   		 koi8r.8x8.psfu   
FILES+= koi8u_8x14.psfu   	 koi8u_8x16.psfu   	 koi8u_8x8.psfu   
FILES+= lat0-08.psfu   		 lat0-10.psfu   	 lat0-12.psfu   
FILES+= lat0-14.psfu   		 lat0-16.psfu   	 lat1-08.psfu   
FILES+= lat1-10.psfu   		 lat1-12.psfu   	 lat1-14.psfu   
FILES+= lat1-16.psfu   		 lat2-08.psfu   	 lat2-10.psfu   
FILES+= lat2-12.psfu   		 lat2-14.psfu   	 lat2-16.psfu   
FILES+= lat2a-16.psfu   	 lat4-08.psfu   	 lat4-10.psfu   
FILES+= lat4-12.psfu   		 lat4-14.psfu   	 lat4-16+.psfu   
FILES+= lat4-16.psfu   		 lat4-19.psfu   	 lat4a-08.psfu   
FILES+= lat4a-10.psfu   	 lat4a-12.psfu   	 lat4a-14.psfu   
FILES+= lat4a-16+.psfu   	 lat4a-16.psfu   	 lat4a-19.psfu   
FILES+= lat5-12.psfu   		 lat5-14.psfu   	 lat5-16.psfu   
FILES+= lat7-14.psfu   		 lat7a-14.psfu   	 lat7a-16.psf   
FILES+= lat9-08.psf   		 lat9-10.psf   		 lat9-12.psf   
FILES+= lat9-14.psf   		 lat9-16.psf   		 lat9u-08.psfu   
FILES+= lat9u-10.psfu   	 lat9u-12.psfu   	 lat9u-14.psfu   
FILES+= lat9u-16.psfu   	 lat9v-08.psfu   	 lat9v-10.psfu   
FILES+= lat9v-12.psfu   	 lat9v-14.psfu   	 lat9v-16.psfu   
FILES+= lat9w-08.psfu   	 lat9w-10.psfu   	 lat9w-12.psfu   
FILES+= lat9w-14.psfu   	 lat9w-16.psfu   	 ruscii_8x16.psfu   
FILES+= ruscii_8x8.psfu   	 sun12x22.psfu   	 t.fnt   
FILES+= t850b.fnt   		 tcvn8x16.psf   	 viscii10-8x16.psfu   

FILESDIR=	${BINDIR}/consolefonts
.PATH:		${.CURDIR}/../../../dist/kbd/data/consolefonts

.include <bsd.prog.mk>
.include <bsd.subdir.mk>
