#	$ssdlinux: Makefile,v 1.1.1.1 2002/05/02 13:37:12 kanoh Exp $
#	$NetBSD: Makefile,v 1.4 1999/02/13 02:54:57 lukem Exp $
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	uudecode
MKMAN=	no

.include <bsd.prog.mk>
