#	$ssdlinux: Makefile,v 1.2 2004/06/18 06:07:09 yamagata Exp $

.include <bsd.own.mk>

SUBDIR= netboot stage2 stage1 lib grub util
# stage2 for initrd
SUBDIR+= stage2_initrd

.include <bsd.subdir.mk>

