#	$ssdlinux: Makefile,v 1.26 2005/03/16 06:48:30 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	postfix-
DISTVERSION=	2.2.1
MASTER_SITES=	ftp://postfix.cloud9.net/official
DEPENDENT=	lib/postfix libexec/postfix usr.sbin/postfix

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
