#	$ssdlinux: Makefile,v 1.25 2005/02/14 01:32:56 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	automake-
DISTVERSION=	1.9.5
EXTRACT_SUFX=	tar.bz2
GNU_DIST=	yes
DEPENDENT=	usr.bin/automake

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
