#	$ssdlinux: Makefile.cflags,v 1.3 2004/12/06 02:21:17 yamagata Exp $

CPPFLAGS=	-DLISPCODE -DCHDIR -DFASTTAG -DUCVISUAL -DMB -DBIT8
CPPFLAGS+=	-DVMUNIX
CPPFLAGS+=	-DEXRECOVER=\"/usr/libexec/exrecover\" \
		-DEXPRESERVE=\"/usr/libexec/expreserve\"
