#	$ssdlinux: Makefile,v 1.2 2004/08/05 02:49:18 yamagata Exp $

.include <bsd.own.mk>

LIB=	history
SRCS=	history.c histexpand.c histfile.c histsearch.c shell.c \
	mbutil.c xmalloc.c
MAN=	${LIB}.3

.include <bsd.lib.mk>
