#	$ssdlinux: Makefile,v 1.3 2002/07/16 01:26:09 yamagata Exp $
#	$NetBSD: Makefile,v 1.3 2001/09/02 22:16:58 wiz Exp $

FILES=		texi2dvi
FILESMODE=	${BINMODE}
MAN=		${FILES}.1

.include <bsd.prog.mk>

.PATH:		${DIST}/texinfo/util ${DIST}/texinfo/doc
