#	$ssdlinux: Makefile,v 1.5 2004/12/15 08:35:27 todoroki Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	zebra-
DISTVERSION=	0.94
MASTER_SITES=	ftp://ftp.zebra.org/pub/zebra
DEPENDENT=	usr.sbin/zebra
DEPENDENT+=	distrib/powerpc-obs2xx/standard/initrd/list_in/zebra

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
