#	$ssdlinux: Makefile,v 1.2 2002/06/06 06:08:51 yamagata Exp $

.include <bsd.own.mk>

PROG=		smtp-source
MKMAN=		no

DIST=		${.CURDIR}/../../../dist/postfix
.PATH:		${DIST}/src/smtpstone

.include <bsd.prog.mk>
