#	$ssdlinux: Makefile,v 1.3 2005/03/16 08:00:45 yamagata Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	strace-
DISTVERSION=	4.5.10
EXTRACT_SUFX=	tar.bz2
MASTER_SITES=	http://jaist.dl.sourceforge.net/sourceforge/strace
DEPENDENT=	usr.bin/strace

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
