#	$ssdlinux: Makefile,v 1.1 2003/12/15 09:05:01 yamagata Exp $

.include <bsd.own.mk>

MODULE=		pnp
MODULEOBJ=	pnp_stub.o pnp_proc.o pnp_bios.o
MKMAN=		no

.include "../Makefile.cflags"

.include <bsd.prog.mk>
