#	$ssdlinux: Makefile,v 1.2 2002/05/25 18:35:21 kanoh Exp $

.include "${.CURDIR}/../../share/mk/bsd.own.mk"
.include "${.CURDIR}/../Makefile.inc"

DISTNAME=	patch-
DISTVERSION=	2.5.4
GNU_DIST=	yes
DEPENDENT=	usr.bin/patch

.include "${.CURDIR}/../../share/mk/bsd.mkdist.mk"
